roundPosition: false
portalSupport: false
hostnameSupport: false
messageOnHostnameTeleportToWorld: true
teleportMessages: true
saveMessages: true
hostnames:
 creative:
  hostname: creative.mike724.com
  world: creative